-- AlterTable
ALTER TABLE "customers" ADD COLUMN     "billingCity" TEXT,
ADD COLUMN     "billingCountry" TEXT,
ADD COLUMN     "billingPostcode" TEXT,
ADD COLUMN     "billingStateRegion" TEXT,
ADD COLUMN     "billingStreet" TEXT,
ADD COLUMN     "code" TEXT,
ADD COLUMN     "defaultDocumentDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "defaultPaymentTerm" TEXT,
ADD COLUMN     "defaultShippingMethod" TEXT,
ADD COLUMN     "defaultShippingTerm" TEXT,
ADD COLUMN     "defaultTaxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "internalNotes" TEXT,
ADD COLUMN     "shippingCity" TEXT,
ADD COLUMN     "shippingCountry" TEXT,
ADD COLUMN     "shippingPostcode" TEXT,
ADD COLUMN     "shippingStateRegion" TEXT,
ADD COLUMN     "shippingStreet" TEXT,
ADD COLUMN     "vatNumber" TEXT,
ADD COLUMN     "website" TEXT;

-- AlterTable
ALTER TABLE "contacts" ADD COLUMN     "isPrimary" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "jobTitle" TEXT;

-- AlterTable
ALTER TABLE "quotes" ADD COLUMN     "billingCity" TEXT,
ADD COLUMN     "billingCountry" TEXT,
ADD COLUMN     "billingPostcode" TEXT,
ADD COLUMN     "billingStateRegion" TEXT,
ADD COLUMN     "billingStreet" TEXT,
ADD COLUMN     "contactEmail" TEXT,
ADD COLUMN     "contactName" TEXT,
ADD COLUMN     "contactPhone" TEXT,
ADD COLUMN     "customerReference" TEXT,
ADD COLUMN     "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "documentDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "internalNotes" TEXT,
ADD COLUMN     "paymentTerm" TEXT,
ADD COLUMN     "promisedDate" TIMESTAMP(3),
ADD COLUMN     "quoteDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "salespersonEmail" TEXT,
ADD COLUMN     "salespersonName" TEXT,
ADD COLUMN     "shippingCity" TEXT,
ADD COLUMN     "shippingCountry" TEXT,
ADD COLUMN     "shippingMethod" TEXT,
ADD COLUMN     "shippingPostcode" TEXT,
ADD COLUMN     "shippingStateRegion" TEXT,
ADD COLUMN     "shippingStreet" TEXT,
ADD COLUMN     "shippingTerm" TEXT,
ADD COLUMN     "subtotalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxMode" TEXT NOT NULL DEFAULT 'exclusive',
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "validityDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "quote_lines" ADD COLUMN     "deliveryDateOverride" TIMESTAMP(3),
ADD COLUMN     "description" TEXT,
ADD COLUMN     "itemCode" TEXT,
ADD COLUMN     "itemName" TEXT,
ADD COLUMN     "lineDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'pcs';

-- AlterTable
ALTER TABLE "sales_orders" ADD COLUMN     "billingCity" TEXT,
ADD COLUMN     "billingCountry" TEXT,
ADD COLUMN     "billingPostcode" TEXT,
ADD COLUMN     "billingStateRegion" TEXT,
ADD COLUMN     "billingStreet" TEXT,
ADD COLUMN     "contactEmail" TEXT,
ADD COLUMN     "contactName" TEXT,
ADD COLUMN     "contactPhone" TEXT,
ADD COLUMN     "customerReference" TEXT,
ADD COLUMN     "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "documentDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "internalNotes" TEXT,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "orderDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "paymentTerm" TEXT,
ADD COLUMN     "promisedDate" TIMESTAMP(3),
ADD COLUMN     "salespersonEmail" TEXT,
ADD COLUMN     "salespersonName" TEXT,
ADD COLUMN     "shippingCity" TEXT,
ADD COLUMN     "shippingCountry" TEXT,
ADD COLUMN     "shippingMethod" TEXT,
ADD COLUMN     "shippingPostcode" TEXT,
ADD COLUMN     "shippingStateRegion" TEXT,
ADD COLUMN     "shippingStreet" TEXT,
ADD COLUMN     "shippingTerm" TEXT,
ADD COLUMN     "subtotalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxMode" TEXT NOT NULL DEFAULT 'exclusive',
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "sales_order_lines" ADD COLUMN     "deliveryDateOverride" TIMESTAMP(3),
ADD COLUMN     "description" TEXT,
ADD COLUMN     "itemCode" TEXT,
ADD COLUMN     "itemName" TEXT,
ADD COLUMN     "lineDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'pcs';

-- CreateIndex
CREATE UNIQUE INDEX "customers_code_key" ON "customers"("code");
